---
title: "PSTAT 174 Project"
author: "Sriharsha Addepalli"
date: "11/16/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo = F}
library (astsa )
library (tseries)
library (MASS)
library (forecast)
library (TSA)
library (GeneCycle)
library (ggplot2)
library(qpcR)
spec.arma <- function(ar=0,ma=0,var.noise=1,n.freq=500, ...)
{ 
    # check causality
     ar.poly <- c(1, -ar)
     z.ar <- polyroot(ar.poly)
     if(any(abs(z.ar) <= 1)) cat("WARNING: Model Not Causal", "\n")  
    # check invertibility
     ma.poly <- c(1, ma)
     z.ma <- polyroot(ma.poly)
     if(any(abs(z.ma) <= 1)) cat("WARNING: Model Not Invertible", "\n")
     if(any(abs(z.ma) <= 1) || any(abs(z.ar) <= 1) ) stop("Try Again")
    #
    ar.order <- length(ar)
    ma.order <- length(ma) 
    # check (near) parameter redundancy [i.e. are any roots (approximately) equal]  
       for (i in 1:ar.order) {
       if ( (ar == 0 & ar.order == 1) || (ma == 0 & ma.order ==1) ) break
       if(any(abs(z.ar[i]-z.ma[1:ma.order]) < 1e-03)) {cat("WARNING: Parameter Redundancy", "\n"); break}
       }
    #
    freq <- seq.int(0, 0.5, length.out = n.freq)
            cs.ar <- outer(freq, 1:ar.order, function(x, y) cos(2 * 
                pi * x * y)) %*% ar
            sn.ar <- outer(freq, 1:ar.order, function(x, y) sin(2 * 
                pi * x * y)) %*% ar
            cs.ma <- outer(freq, 1:ma.order, function(x, y) cos(2 * 
                pi * x * y)) %*% -ma
            sn.ma <- outer(freq, 1:ma.order, function(x, y) sin(2 * 
                pi * x * y)) %*% -ma                      
    spec <- var.noise*((1 - cs.ma)^2 + sn.ma^2)/((1 - cs.ar)^2 + sn.ar^2)
    spg.out <- list(freq=freq, spec=spec)
    class(spg.out) <- "spec"
    plot(spg.out, ci=0, main="", ...)
    return(invisible(spg.out))
}

plot.roots <- function(ar.roots=NULL, ma.roots=NULL, size=2, angles=FALSE, special=NULL, sqecial=NULL,my.pch=1,first.col="blue",second.col="red",main=NULL)
{xylims <- c(-size,size)
      omegas <- seq(0,2*pi,pi/500)
      temp <- exp(complex(real=rep(0,length(omegas)),imag=omegas))
      plot(Re(temp),Im(temp),typ="l",xlab="x",ylab="y",xlim=xylims,ylim=xylims,main=main)
      abline(v=0,lty="dotted")
      abline(h=0,lty="dotted")
      if(!is.null(ar.roots))
        {
          points(Re(1/ar.roots),Im(1/ar.roots),col=first.col,pch=my.pch)
          points(Re(ar.roots),Im(ar.roots),col=second.col,pch=my.pch)
        }
      if(!is.null(ma.roots))
        {
          points(Re(1/ma.roots),Im(1/ma.roots),pch="*",cex=1.5,col=first.col)
          points(Re(ma.roots),Im(ma.roots),pch="*",cex=1.5,col=second.col)
        }
      if(angles)
        {
          if(!is.null(ar.roots))
            {
              abline(a=0,b=Im(ar.roots[1])/Re(ar.roots[1]),lty="dotted")
              abline(a=0,b=Im(ar.roots[2])/Re(ar.roots[2]),lty="dotted")
            }
          if(!is.null(ma.roots))
            {
              sapply(1:length(ma.roots), function(j) abline(a=0,b=Im(ma.roots[j])/Re(ma.roots[j]),lty="dotted"))
            }
        }
      if(!is.null(special))
        {
          lines(Re(special),Im(special),lwd=2)
        }
      if(!is.null(sqecial))
        {
          lines(Re(sqecial),Im(sqecial),lwd=2)
        }
        }
```

```{r dataexplore}
const <- read.csv("/Users/sriadd/Downloads/total-construction-spending-residential.csv")
const_res <- ts(const[,2],frequency = 1)
plot.ts(const_res, main = "Residential Construction Spending from Jan 2002 - Sep 2018", xlab = "Time in Months",
                ylab = "Construction Cost")
seasonplot(const_res,12, col = rainbow(16), year.labels = T, main = "Seasonal Plot of Residential Construction Costs")
```

```{r}
require(MASS)
bc <- boxcox(const_res ~ as.numeric(1:length(const_res)))
lambda <- bc$x[which(bc$y == max(bc$y))] #lambda = 0.4646
trans_const <- const_res ^ lambda
trans_const1 <- ts(trans_const [1:(length(const_res) - 10)])
plot(trans_const1, main = "Transformed Residential Construction Spending 
     from Jan 2002 - Nov 2017", xlab = "Time in Months",
                ylab = "Transformed Construction Cost")
op <- par(mfrow = c(1,2))
acf(trans_const1, lag.max = 50, main = "ACF of Transformed Data")
pacf(trans_const1, lag.max = 50, main = "PACF of Transformed Data")
par(op)
const.diff <- diff(trans_const1, lag = 12)
plot(const.diff, main=expression(nabla[12] ~ "Transformed Data") , xlab = "Time in Months",
                ylab = "")
const.diff.nt <- diff(const.diff, differences = 1, lag = 1)
var(const.diff.nt)

op <- par(mfrow = c(1,2))
plot(const.diff.nt, main=expression(nabla ~ nabla[12] ~ "Transformed Data") , xlab = "Time in Months",
                ylab = "")
plot(diff(const.diff,differences = 2, lag = 1), main=expression(nabla[2] ~ nabla[12] ~ "Transformed Data") , xlab = "Time in Months",
                ylab = "")
par(op)

op <- par(mfrow = c(1,2))
acf(diff(const.diff,differences = 2, lag = 1), lag.max = 50, main = expression("ACF of " ~ nabla[2] ~ nabla[12] ~ "Transformed Data"))
pacf(diff(const.diff,differences = 2, lag = 1), lag.max = 50, main = expression("PACF of " ~ nabla[2] ~ nabla[12] ~ "Transformed Data"))
par(op)

```

```{r}
#for (i in 0:4){
#  for (j in 0:4){ 
#    print(i); 
#    print(j); 
#    print(AICc(arima(const.diff.nt,order = c(i,0,j), method = "ML")))
#  }
#}

AICc <- numeric()
for (p in 0:4) {
  for (q in 0:4) {
    AICc <- c(AICc , sarima(trans_const1, p, 1, q, 1, 1, 0, 12, details=FALSE)$AICc)
  }
}
AICc <- matrix(AICc ,nrow=5,byrow=TRUE)
rownames(AICc) <- c("p=0" , "p=1" , "p=2", "p=3", "p=4")
colnames (AICc) <- c("q=0" , "q=1" , "q=2", "q=3", "q=4" )
AICc <- data.frame(AICc)
AICc

```
$SARIMA (4,1,4)$ x $(1,1,0)_{12}$ = 1.2114
$SARIMA (2,1,0)$ x $(1,1,0)_{12}$ = 1.2326
$SARIMA (4,1,3)$ x $(1,1,0)_{12}$ = 1.1952
$SARIMA (2,1,1)$ x $(1,1,0)_{12}$ = 1.2302

```{r}
fit1 <- arima(trans_const1, order = c(4,1,4), seasonal = list(order = c(1,1,0), period = 12), method = "ML")
fit2 <- arima(trans_const1, order = c(2,1,0), seasonal = list(order = c(1,1,0), period = 12), method = "ML")
fit3 <- arima(trans_const1, order = c(4,1,3), seasonal = list(order = c(1,1,0), period = 12), method = "ML")
fit4 <- arima(trans_const1, order = c(2,1,1), seasonal = list(order = c(1,1,0), period = 12), method = "ML")
fit1
fit2
fit3
fit4

```

```{r}
#Fit1
op <- par(mfrow = c(2,3))
plot.roots(NULL, polyroot(c(1,-0.2811,-0.2485,-0.1260 ,0.6951)), main = "roots for ar part")
plot.roots(NULL, polyroot(c(1,0.7612,0.8259,0.5512,-0.2725)), main ="roots for ma part")
plot.roots(NULL, polyroot(c(1,-0.2474)), main ="roots for sar part") # causal and invertible
par(op)

#Fit2
op <- par(mfrow = c(2,3))
plot.roots(NULL, polyroot(c(1,0.4476,0.1723)), main = "roots for ar part")
plot.roots(NULL, polyroot(c(1,-0.1600)), main = "roots for sar part")
par(op)

#Fit3
op <- par(mfrow = c(2,3))
plot.roots(NULL, polyroot(c(1,0.3296,-0.0689,-0.6734,0.5177)), main = "roots for ar part")
plot.roots(NULL, polyroot(c(1,0.1278,0.3141,0.8728)), main ="roots for ma part")
plot.roots(NULL, polyroot(c(1,-0.1722)), main = "roots for sar part")
par(op)

#Fit4
op <- par(mfrow = c(2,3))
plot.roots(NULL, polyroot(c(1,-0.3553,0.5599)), main = "roots for ar part")
plot.roots(NULL, polyroot(c(1,0.8748)), main ="roots for ma part")
plot.roots(NULL, polyroot(c(1,-0.1921)), main = "roots for sar part")
par(op)
```

```{r diagnostics}
#NORMALITY
res1 <- residuals(fit1)
res2 <- residuals(fit2)
res3 <- residuals(fit3)
res4 <- residuals(fit4)

op <- par(mfrow = c(1,2)) # DO NOT INCLUDE, NOT STATIONARY/INVERTIBLE
hist(res1, main = "Histogram of Residuals of Model 1", breaks = 15)
qqnorm(res1, main = "QQ plot of Model 1")
qqline(res1)
par(op)

op <- par(mfrow = c(1,2))
hist(res2, main = "Histogram of Residuals of Model 2", breaks = 15)
qqnorm(res2, main = "QQ plot of Model 2")
qqline(res2)
par(op)

op <- par(mfrow = c(1,2))# DO NOT INCLUDE, NOT STATIONARY/INVERTIBLE
hist(res3, main = "Histogram of Residuals of Model 3", breaks = 15)
qqnorm(res3, main = "QQ plot of Model 3")
qqline(res3)
par(op)

op <- par(mfrow = c(1,2))
hist(res4, main = "Histogram of Residuals of Model 4", breaks = 15)
qqnorm(res4, main = "QQ plot of Model 4")
qqline(res4)
par(op)


shapiro.test(res1)# DO NOT INCLUDE, NOT STATIONARY/INVERTIBLE
shapiro.test(res2)
shapiro.test(res3)# DO NOT INCLUDE, NOT STATIONARY/INVERTIBLE
shapiro.test(res4)

#INDEPENDENCE/CORRELATION
box1 <- Box.test(res1, lag = 12, type = "Box-Pierce", fitdf = 6)# DO NOT INCLUDE, NOT STATIONARY/INVERTIBLE
box2 <- Box.test(res2, lag = 12, type = "Box-Pierce", fitdf = 2)
box3 <- Box.test(res3, lag = 12, type = "Box-Pierce", fitdf = 5)# DO NOT INCLUDE, NOT STATIONARY/INVERTIBLE
box4 <- Box.test(res2, lag = 12, type = "Box-Pierce", fitdf = 3)
box1
box2
box3
box4


acf(res1)
pacf(res1)

op <- par(mfrow = c(1,2))
acf(res2, main = "ACF of Model 2")
pacf(res2, main = "PACF of Model 2")
par(op)


acf(res3)
pacf(res3)

op <- par(mfrow = c(1,2))
acf(res4, main ="ACF of Model 4")
pacf(res4, main = "PACF of Model 4")
par(op)

#our final model is Model 2, SARIMA (2,1,0) x (1,1,0)12
```

```{r forecasting}

pred.tr <- predict(fit2, n.ahead = 10)
upper <- pred.tr$pred + 2*pred.tr$se
lower <- pred.tr$pred - 2*pred.tr$se
ts.plot(trans_const1, xlim = c(1, length(trans_const1)+10), main ="Forecasting Transformed Data", ylab = "Transformed Construction Cost")
lines(upper, col = "BLUE", lty = "dashed")
lines(lower, col = "BLUE", lty = "dashed")
points((length(trans_const1) +1):(length(trans_const1)+10), pred.tr$pred, col = "red", pch = 16, cex = 0.5)

pred.origin <- pred.tr$pred ^ (1/lambda)
uorig <- upper ^ (1/lambda)
lorig <- lower ^ (1/lambda)
const_res2 <- const_res
ts.plot(const_res2, xlim = c(1, length(const_res2)), main ="Forecasting Original Data", ylab = "Construction Spending")
lines(uorig, col = "BLUE", lty = "dashed")
lines(lorig, col = "BLUE", lty = "dashed")
points((length(trans_const1) +1):(length(trans_const1)+10), pred.origin, col = "red", pch = 16, cex = 0.5)


ts.plot((const_res2), xlim = c(length(const_res2) - 20, length(const_res2)), main = "Comparison of Forecasted Values and Original Values",
        ylab = "Construction Costs")
points(192:201, const_res2[192:201], col = "GREEN")
points(192:201, pred.origin, col = "RED")
points(192:201, uorig, lty = 1, col = "BLUE")
points(192:201, lorig, lty = 1, col = "BLUE")

```
```{r}
points((length(trans_const1) + 1):(length(trans_const1) + 10), const_res2[192:201], col = "GREEN")
points((length(trans_const1) + 1):(length(trans_const1) + 10), pred.origin, col = "RED")
lines((length(trans_const1) + 1):(length(trans_const1) + 10), uorig, lty = 2, col = "blue")
lines((length(trans_const1) + 1):(length(trans_const1) + 10), lorig, lty = 2, col = "blue")

```














